power: Ignore unused parameter errors
vendor/qcom/opensource/power/power-common.c:62:60: error: unused parameter 'hint' [-Werror,-Wunused-parameter]
int __attribute__((weak)) power_hint_override(power_hint_t hint, void* data) {
                                                           ^
vendor/qcom/opensource/power/power-common.c:62:72: error: unused parameter 'data' [-Werror,-Wunused-parameter]
int __attribute__((weak)) power_hint_override(power_hint_t hint, void* data) {
                                                                       ^
vendor/qcom/opensource/power/power-common.c:100:56: error: unused parameter 'on' [-Werror,-Wunused-parameter]
int __attribute__((weak)) set_interactive_override(int on) {

vendor/qcom/opensource/power/utils.c:215:22: error: unused parameter 'duration' [-Werror,-Wunused-parameter]
void interaction(int duration, int num_args, int opt_list[]) {
                     ^
vendor/qcom/opensource/power/utils.c:215:36: error: unused parameter 'num_args' [-Werror,-Wunused-parameter]
void interaction(int duration, int num_args, int opt_list[]) {
                                   ^
vendor/qcom/opensource/power/utils.c:215:50: error: unused parameter 'opt_list' [-Werror,-Wunused-parameter]
void interaction(int duration, int num_args, int opt_list[]) {